set -g prefix C-a
unbind-key C-b
bind-key C-a send-prefix
set -s escape-time 10
set -g default-terminal "tmux-256color"
set-option -ga terminal-overrides ",xterm-ghostty:Tc"
set-option -ga terminal-overrides ",xterm-ghostty:RGB"
set -as terminal-overrides ',xterm-ghostty:Smulx=\E[4::%p1%dm'
set -as terminal-overrides ',xterm-ghostty:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d;m'
set -g focus-events on
set -g allow-passthrough on
set -s set-clipboard on
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi 'v' send-keys -X begin-selection
bind-key -T copy-mode-vi 'y' send-keys -X copy-selection-and-cancel
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
set -g status-left ''
set -g status-right ''
set -g status-style bg=colour208
set-option -g set-titles on
set-option -g set-titles-string "#h"
set-option -g history-limit 25000
set -g automatic-rename on
set -g status-interval 2
set-window-option -g xterm-keys on
set -s extended-keys on
set -g automatic-rename-format '#(PROG="#{pane_current_command}"; GIT_DIR=$(git -C #{pane_current_path} rev-parse --show-toplevel 2>/dev/null); if [ "$PROG" != "bash" ] && [ "$PROG" != "zsh" ] && [ "$PROG" != "sh" ]; then echo "$PROG"; elif [ -n "$GIT_DIR" ]; then basename "$GIT_DIR"; else basename "#{pane_current_path}"; fi)'
