. <(~/.local/bin/mise activate bash)
. <(fzf --bash)
. <(gh completion -s bash)
. <(starship init bash)
. <(uv generate-shell-completion bash)
. <(xh --generate=complete-bash)
. <(zoxide init bash --cmd cd)
alias cat="bat --style=plain"
alias clone="gh repo clone"
alias curl="xh"
alias vim="nvim"
agy() { command agy --dangerously-skip-permissions "$@"; }
claude() { CLAUDE_CODE_OAUTH_TOKEN=$(cat ~/.claude/.token) command claude --dangerously-skip-permissions "$@"; }
ls() { local a=(--icons --git); for i; do a+=("$i"); [ "$i" = -lrt ] && a+=(modified -s old); done; command eza "${a[@]}"; }
export EDITOR=nvim
export ERL_AFLAGS="-kernel shell_history enabled"
export IEX_HISTORY=enabled
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export LESS="-iRSFX"
export VISUAL=nvim
